rootProject.name = 'scholario'

include 'scholario-book-module'
include 'app'
include 'scholario-user-module'
include 'scholario-reserve-module'
include 'scholario-course-module'
include 'scholario-lending-module'
include 'scholario-notification-module'
include 'scholario-royalty-module'
include 'scholario-content-module'
include 'scholario-analytics-module'
include 'scholario-recommendation-module'

include 'scholario-review-module'
include 'scholario-auth-module'
include 'scholario-violation-module'