plugins {
    id 'org.springframework.boot' version '4.0.6' apply false
    id 'io.spring.dependency-management'
}

dependencies {
    implementation project(':scholario-user-module')
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-graphql'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-graphql-test'
    testImplementation 'io.projectreactor:reactor-test'
}