type Query {
    getBookById(id: ID!): Book
    searchBooks(title: String, isbn: String): [Book]
    getBooksByFaculty(facultyId: ID!): [Book]
    getBookVersions(bookId: ID!): [Book]
}

type Mutation {
    createBook(input: BookInput!): Book
    updateBook(id: ID!, input: BookInput!): Book
    deleteBook(id: ID!): Book
    publishBook(id: ID!): Book
    archiveBook(id: ID!): Book
    versionBook(input: BookVersionInput!): Book
}

type Book {
    id: ID
    title: String
    isbn: String
    facultyId: ID
    description: String
    versionNumber: Int
    state: BookState
    parentBookId: ID
    createdAt: String
    updatedAt: String
}

interface BookState {
    type: String
}

type Draft implements BookState {
    type: String
}

type Review implements BookState {
    type: String
}

type Published implements BookState {
    type: String
}

type Archived implements BookState {
    type: String
}

input BookInput {
    title: String!
    isbn: String!
    facultyId: ID!
    description: String
}

input BookVersionInput {
    parentBookId: ID!
    title: String
    isbn: String!
    description: String
}
